### ISSUE TITLE
Add shop descriptions for bonus upgrades

### ISSUE THREAD

**Issue by toadettexmushina** [ori-rando/wotw-seedgen#58]
Vanilla upgrades have descriptions of what they do in the shop, bonus upgrades should as well.

Since bonus upgrades are added by a header, we might need to allow descriptions to be added to custom pickups in general.

**Comment by SiriusAshling** [comment]
Directly placed bonus items could set this through the existing shop commands, to support the descriptions for pool items probably a `!!description` tool should be added

**Comment by SiriusAshling** [comment]
Gathering descriptions form the base game since it would be nice if we could achieve a similar style:

- **Energy**: Gain x additional Energy cells (depending on upgrade amount, also includes a "Next Level" section in yellow)
- **Vitality**: Gain x additional Life cells (as above)
- **Wingclip**: Deal bonus damage to flying enemies
- **Finesse**: x% change to deal 50% bonus damage
- **Light Harvest**: Enemies drop 4 extra Spirit Light orbs
- **Overcharge**: Reduce Energy costs by 50% and increase damage taken by 100%
- **Swap**: Swap maximum life and energy
- **Triple Jump**: Jump twice mid-air before landing
[...more in upgrade screen]
- **Sentry**: \*Uses Energy\* Spawn a spirit orb that attacks for you
- **Sentry Speed**: Increase Sentry attack speed
- **Spirit Star**: \*Uses Energy\* Throw a star that returns to you
- **Spirit Star**: Tap to pause the Spirit Star's flight and spin it in place
- **Blaze**: \*Uses Energy\* Set nearby enemies on fire
- **Charge Blaze**: \*Uses Energy\* Charge up a flame to damage and set all enemies in sight on fire
- **Spirit Smash**: Pound foes with a strong, sweeping blow. Destroys unstable ground
- **Shock Smash**: Drop attacks with Spirit Smash create a shockwave
- **Spike**: \*Uses Energy\* Throw a powerful spear of light. Uses a large amount of Energy. Destroys unstable ground
- **Exploding Spike**: Spike explodes on hit
- **Water Breath**: Breathe under water
- **Fast Travel**: Select Spirit Wells on the map and #warp# to them #from anywhere#.

**Comment by SiriusAshling** [comment]
Suggestions for item descriptions more oriented towards the "imperative" style moon went for and using wordings from existing shards:
- **Health Regeneration**: Replenish Health over time
- **Energy Regeneration**: Replenish Energy over time
- **Extra Double Jump**: Jump an additional time mid-air before landing
- **Extra Air Dash**: Dash an additional time mid-air before landing
- **Blaze Efficiency**: Reduce Blaze Cost by 50%
[...more efficiencies]
- **Rapid Smash**: Spirit Smash attacks are faster
[...more rapids]
- **Melting Blaze**: Blaze melts ice and ignites lanterns
[...more melts]
- **Uncharged Bashgrenades**: Bash your Grenades without charging them first on the ground
- **Extra Grenade**: Use multiple Grenades at once
- **Splinter Grenade**: Throw 2 additional Grenades
